CREATE TABLE IF NOT EXISTS "ROLL_TABLE_ENTRY" (
	`entryId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`tableId`	INTEGER,
	`minRoll`	INTEGER,
	`maxRoll`	INTEGER,
	`result`	TEXT,
	`rerollTableId`	INTEGER,
	`dieQty`	INTEGER,
	`dieSize`	INTEGER,
	`rollMul`	INTEGER DEFAULT 1,
	`rollAvg`	INTEGER
);
CREATE TABLE IF NOT EXISTS "ROLL_TABLE" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`dieQty`	INTEGER,
	`dieSize`	INTEGER
);
PRAGMA user_version = 8;
