CREATE TABLE IF NOT EXISTS `LISTS` ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `name` TEXT );
CREATE TABLE IF NOT EXISTS "LIST_ITEMS" ( `itemId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `listId` INTEGER, `table` TEXT, `fieldId` INTEGER, `metaData` TEXT );
PRAGMA user_version = 5;
